### ISSUE TITLE
msumacm.org domain expires on 9/18

### ISSUE THREAD

**Issue by kadimisetty** [MSUM-ACM/MSUM-ACM.github.io#1]
@humphreyja 

**To transfer Domain**:
Details for my registrar "Namecheap" —
https://www.namecheap.com/support/knowledgebase/article.aspx/255/83/what-should-i-do-to-transfer-a-domain-to-namecheap

**If you'd rather me extend it** and do a transfer later. Let me know before 9/18. the renewal fee is $12.48 I can either pick up cash or receive money here —
https://cash.me/$kadimisetty

Let me know what you wanna do

**Comment by kadimisetty** [comment]
Option 3: @humphreyja  I can also just let it expire and you purchase it right away the next day I believe. Although, in this case, theres a chance the registrar might hike up the price for repurchasing or hold the domain for a while before making it available.

**Comment by humphreyja** [comment]
I will try to do a transfer.

**Comment by humphreyja** [comment]
it says it needs my email as the admin contact for the transfer.  Use humphreyja@mnstate.edu.  My user name is humphreyja.  I think you need to transfer it.

**Comment by kadimisetty** [comment]
Apparently I need an authentication code.
I'm also assuming `humphreyja` is your namecheap username.
The error-
<img width="724" alt="screen shot 2015-08-27 at 9 21 28 am" src="https://cloud.githubusercontent.com/assets/535947/9522954/2aafcb5c-4c9d-11e5-83de-1fab2adad2bb.png">


The transfer screen on my end; if it helps:
<img width="1260" alt="screen shot 2015-08-27 at 9 23 54 am" src="https://cloud.githubusercontent.com/assets/535947/9522989/5ec277b4-4c9d-11e5-94c5-2fa6322868fc.png">

**Comment by humphreyja** [comment]
haha.  what a process.  Here use this: 9C353FC574

**Comment by kadimisetty** [comment]
Apaarently need your contact info now.
<img width="725" alt="screen shot 2015-08-27 at 4 38 24 pm" src="https://cloud.githubusercontent.com/assets/535947/9533796/171c792c-4cda-11e5-9968-f3e24c59fd97.png">

**Comment by humphreyja** [comment]
![image](https://cloud.githubusercontent.com/assets/6947247/9550145/3c11eaf6-4d6f-11e5-9119-5f78b167ab19.png)

**Comment by humphreyja** [comment]
Use that info

**Comment by kadimisetty** [comment]
K Done. 
hey dont forget to remove your personal info here before closing issue.

**Comment by humphreyja** [comment]
K done.  Thanks Sri!
