### ISSUE TITLE
Layout Design for v2

### ISSUE THREAD

**Issue by kadimisetty** [MSUM-ACM/MSUM-ACM.github.io#14]
w/ junk content
![Home tablet portrait](https://cloud.githubusercontent.com/assets/535947/4691688/418c1990-572d-11e4-9b02-5c5fcc9f8831.png)
![Detail tablet portrait](https://cloud.githubusercontent.com/assets/535947/4691692/5814bcb2-572d-11e4-8152-7e3de30548a8.png)

**Comment by humphreyja** [comment]
Keeping this open for possibilities
