### ISSUE TITLE
No Contributing Guidelines

### ISSUE THREAD

**Issue by alunduil** [MSUM-ACM/MSUM-ACM.github.io#19]
There aren't any contributing guidelines for this repository.  We should probably have some set that keeps development moving forward.

**Comment by MoonWolf125** [comment]
As the group grows and so does the website this will be a necessity. I've added this to the current project, assigned, and labeled it. I will most likely rectify this personally.

**Comment by MoonWolf125** [comment]
Added in 8a3daa36d9a45588b76fc27baac62400a2a4103b

**Comment by alunduil** [comment]
I don't see a pull request for that commit.  Do you want to use pull requests as the medium for reviews?  It's got a reasonably good review feature built in.

**Comment by MoonWolf125** [comment]
Yup, my bad, had a small post to add for an email today. PR here: https://github.com/MSUM-ACM/MSUM-ACM.github.io/pull/23

**Comment by alunduil** [comment]
@MoonWolf125 no worries.  I just wanted to be sure I wasn't making that up.
