### ISSUE TITLE
README is missing Getting Started section

### ISSUE THREAD

**Issue by alunduil** [MSUM-ACM/MSUM-ACM.github.io#20]
It's imperative that a README include how new developers can get started, but in the case of a blog the important thing is to outline how someone can contribute a new article of varying classes.

Along with this, I have no idea what structure is being used for this site (I prefer static site generators).  There's not even a travis configuration I can look at to see how things are deployed.  This is necessary because doing a tree of the directory is huge, and an ls doesn't indicate how the site is layed out or what the intention for organization is (which should also be in the README).

**Comment by MoonWolf125** [comment]
Thanks for the insight! I've added this to the project along with some labels. I'll most likely handle this on my own. I put together a small video unlisted on youtube for the officers that are currently going to work on the website to help explain some of this, but I absolutely agree. The README needs to be a thorough explanation of everything.

**Comment by alunduil** [comment]
@MoonWolf125 I think everything is a bit lofty of a goal, but I agree for the common things people need when first looking at the project.  READMEs that include everything don't get read and separate documentation for a project is super important as well (a blog perhaps less so).  These sections would be super useful at any rate.

What kind of code review process have you setup on this repository?

**Comment by MoonWolf125** [comment]
@alunduil That's fair. I guess I was being outlandish with my words. Currently we don't have any review, I'm only having the officers work on their own branches or dev and I'll make any reviews when we make PRs into master.

**Comment by alunduil** [comment]
Hmm, what about adopting git flow until you guys settle into a good development flow?  Typically push to master is only feasible with a good continuous pipeline.

**Comment by MoonWolf125** [comment]
Git flow is what we demonstrated and did the GitWorkshop on. That's essentially what I'm having the officers use. I wasn't aware that it was called Git flow. I've done a couple of master pushes because we needed to update a couple of things immediately on the website. It's easier to just make a website post and link that in a list serve email sent out to the MSUM students.

**Comment by alunduil** [comment]
Yeah, git flow is pretty prescriptive but can help ensure good synchronization points.  It's also hard to get right and requires a bit of developer discipline.  Github has branch protections which make it easier to leverage and I always turn them on for my released projects.  Eventually for something like this, you want it continuous so once a pull request is merged it lands and goes live without any help.
